/** @type {import("tailwindcss").Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        ds: {
          bg: "var(--ds-bg)",
          secondary: "var(--ds-bg-secondary)",
          card: "var(--ds-card)",
          elevated: "var(--ds-elevated)",
          border: "var(--ds-border)",
          divider: "var(--ds-divider)",
          text: "var(--ds-text)",
          "text-secondary": "var(--ds-text-secondary)",
          muted: "var(--ds-text-muted)",
          disabled: "var(--ds-text-disabled)",
          brand: "var(--ds-brand)",
          "brand-hover": "var(--ds-brand-hover)",
          "brand-press": "var(--ds-brand-press)",
          "brand-soft": "var(--ds-brand-soft)",
          success: "var(--ds-success)",
          warning: "var(--ds-warning)",
          danger: "var(--ds-danger)",
          info: "var(--ds-info)",
          chart: "var(--ds-chart)",
        },
        /* Legacy aliases → design system (keep existing classnames working) */
        bg: "var(--ds-bg)",
        surface: "var(--ds-card)",
        "surface-sunk": "var(--ds-elevated)",
        border: "var(--ds-border)",
        "border-strong": "var(--ds-border-strong)",
        olive: "var(--ds-brand)",
        "olive-dark": "var(--ds-brand-press)",
        "olive-tint": "var(--ds-brand-soft)",
        "olive-brown": "var(--ds-text-secondary)",
        ink: "var(--ds-text)",
        "ink-soft": "var(--ds-text-secondary)",
        "ink-faint": "var(--ds-text-muted)",
        red: "var(--ds-danger)",
        "red-tint": "var(--ds-danger-soft)",
        "dark-bg": "#0B0D10",
        "dark-surface": "#15181E",
        "dark-border": "rgba(255,255,255,0.07)",
        "dark-tint": "rgba(244,63,94,0.10)",
      },
      fontFamily: {
        display: ['"Inter"', "system-ui", "sans-serif"],
        sans: ['"Inter"', "system-ui", "sans-serif"],
        mono: ['"Inter"', "ui-monospace", "monospace"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        h1: ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        h2: ["30px", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "600" }],
        h3: ["24px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        large: ["18px", { lineHeight: "1.5" }],
        body: ["16px", { lineHeight: "1.5" }],
        small: ["14px", { lineHeight: "1.5" }],
        caption: ["12px", { lineHeight: "1.5" }],
      },
      spacing: {
        1: "4px",
        2: "8px",
        3: "12px",
        4: "16px",
        5: "24px",
        6: "32px",
        7: "40px",
        8: "48px",
        9: "64px",
        10: "80px",
        11: "96px",
      },
      borderRadius: {
        sm: "10px",
        md: "14px",
        lg: "18px",
        modal: "24px",
        pill: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px rgba(0,0,0,0.06)",
        md: "0 8px 24px rgba(0,0,0,0.08)",
        lg: "0 18px 48px rgba(0,0,0,0.12)",
        glow: "none",
        "glow-lg": "none",
        "focus-brand": "0 0 0 3px var(--ds-brand-ring)",
      },
      transitionDuration: {
        fast: "150ms",
        normal: "180ms",
        slow: "220ms",
        button: "150ms",
        card: "180ms",
        tooltip: "120ms",
        table: "120ms",
        page: "220ms",
        drawer: "220ms",
        modal: "220ms",
        notification: "200ms",
        chart: "250ms",
        hover: "150ms",
        press: "100ms",
        nav: "150ms",
      },
      transitionTimingFunction: {
        premium: "cubic-bezier(0.2, 0, 0, 1)",
      },
      keyframes: {
        riseIn: {
          "0%": { opacity: "0", transform: "translateY(6px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        rowIn: {
          "0%": { opacity: "0", transform: "translateY(4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        riseIn: "riseIn 220ms cubic-bezier(0.2, 0, 0, 1) both",
        rowIn: "rowIn 120ms cubic-bezier(0.2, 0, 0, 1) both",
      },
    },
  },
  plugins: [],
};
